Notebooks

2026

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
#Numeric library 1995
#early 2000 - Numarray
#2005 Numeric+Numarray = Numpy
#written in C, 

#Numpy is 50times faster than Python List

In [5]:
#List vs Numpy arrays

#containes only one type of data like, int, str
#Performance
#Memory effciency
#Vector operation


In [6]:
import numpy as np

In [9]:
#Basic array creation
arr=np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [10]:
a=[1,2,3,'deepak']
a

[1, 2, 3, 'deepak']

In [12]:
arr1=np.array([1,2,3,'Deepak'])
arr1 #all data types converted into string

array(['1', '2', '3', 'Deepak'], dtype='<U21')

In [15]:
arr2=np.array([1,2,3.5])
arr2 #all data types converted into float

array([1. , 2. , 3.5])

In [17]:
#vectors and matrix

a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#1d-vector
#2d-matrix
#above 2d - tensor

In [23]:
#array generation function

a = np.arange(1,11)
b =np.arange(1,11,2)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [24]:
#zeros

arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
#ones
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
#matrix
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
#matrix
arr=np.ones((3,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [36]:
#lins_space
#returned evenly spaced number over specified interval

arr=np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [37]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
#random generation function

#random numbers between 0 & 1

np.random.rand(5)

array([0.7866673 , 0.14053897, 0.61972098, 0.09043258, 0.23010919])

In [42]:
#standardization
#values between -3 to +3

np.random.randn(10)

array([-1.08880636, -0.6097445 ,  1.03538198,  1.86879833,  0.46014251,
        1.43092053,  1.19603344, -0.0148643 , -0.46140102,  0.53780282])

In [44]:
#print any number between 0 to given number

np.random.randint(3)

2

In [46]:
# 10 random number between 3-30
np.random.randint(3,30,10)

array([28, 26,  7, 12, 12, 11, 19, 22, 25,  3], dtype=int32)

In [ ]:
#Array attributes

