Indexing and Slicing

In [1]:
#indexing and slicing

In [3]:
import numpy as np

In [4]:
a=np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
#indexing

a[0]

np.int64(11)

In [7]:
a[7]

np.int64(18)

In [9]:
#slicing
a[1:4]

array([12, 13, 14])

In [10]:
a[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
a[1::3]

array([12, 15, 18])

Numpy indexing and Slicing of Matrix

In [13]:
#Numpy indexing and Slicing of Matrix

arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0] #print 1st row

array([1, 2, 3, 4, 5])

In [ ]:
arr[1] #print 2nd row

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[2] #print 3rd row

array([11, 12, 13, 14, 15])

In [18]:
arr[0,0]

np.int64(1)

In [19]:
arr[5,4]

np.int64(30)

In [22]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [23]:
arr[3:6,3:6]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
#to access coloumn

arr[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [27]:
#Boolean Indexing

arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr=arr[bool_index] #print only True values
arr

array([12, 14, 16, 18, 20])