App Operation

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a2

array([ 6,  7,  8,  9, 10])

In [5]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a2-a1

array([5, 5, 5, 5, 5])

In [12]:
a1//a2

array([0, 0, 0, 0, 0])

In [9]:
a3=np.array([3,4,5,6,7,8])

In [11]:
a1+a3 #error because of size of a3

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [15]:
#Broadcasting

ar=[10,20,30,40]
arr=np.array(ar)

arr+10 #added 10 to all the elements

array([20, 30, 40, 50])

In [17]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2*2 #multiply all the elements with 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [ ]:
#Deep and shallow copy