Matrix Operation

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [4]:
A

array([[1, 2],
       [3, 4]])

In [5]:
B

array([[5, 6],
       [7, 8]])

In [7]:
#Matrix maltiplication

A*B #but this is not how multiply occurs in Matrix

array([[ 5, 12],
       [21, 32]])

In [ ]:
#first row*first coloumn

A@B

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B) #second method 

array([[19, 22],
       [43, 50]])

In [11]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T #transpose, row became coloumn

array([[1, 3],
       [2, 4]])