Advance array manipulation

In [4]:
import numpy as np

In [5]:
#array manipulation

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [6]:
#stacking array

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))  #vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b)) #horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [11]:
#Splitting Array

c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c,3) # 4 elements can not be split in 3 equal part

ValueError: array split does not result in an equal division

In [14]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [15]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [17]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]