Numpy Exercises

In [2]:
import numpy as np

Valid Sudoku

In [5]:
#row sum=45
#column sum=45
#size = 9x9

s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [8]:
b=np.sum(s,axis=1)

In [12]:
c=np.sum(s,axis=0)

In [11]:
for i in b:
    if i!=45:
        print('Sudoku is not valid')
        break
else:
    print('For rows sudoku is valid')


For rows sudoku is valid


In [13]:
for i in c:
    if i!=45:
        print('Sudoku is not valid')
        break
else:
    print('For columns sudoku is valid')

For columns sudoku is valid


In [14]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [15]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
s[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [19]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3,j:j+3]
        print(n.sum())


45
45
45
45
45
45
45
45
45


General questions

In [4]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [30]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [36]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [39]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [40]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [41]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [42]:
#Increase Math marks of all students by 5.

data[:,0]+5

array([23, 24, 22, 23, 25])

In [46]:
#Find how many students are younger than 19.
#len(data[:,1]<19)
len(data[data[:,0]<19])

3

In [ ]:
#Calculate the average marks in each subject (column-wise mean).

maths_mean=np.mean(data[:,1])
maths_mean



np.float64(81.6)

In [52]:
science_mean=np.mean(data[:,2])
science_mean

np.float64(83.2)

In [55]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [56]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:,1] >=80) & (data[:,2]>=80) ]

array([[19, 92, 88],
       [20, 90, 85]])

In [57]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [66]:

#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
#data[data[:,2]<75] =0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])